/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404.vue')['default']
    AutoIconPheyeBold: typeof import('~icons/ph/eye-bold')['default']
    AutoIconPheyeSlashBold: typeof import('~icons/ph/eye-slash-bold')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FooterCustom: typeof import('./src/components/FooterCustom/index.vue')['default']
    FooterCustomOctocat: typeof import('./src/components/FooterCustom/octocat.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld/index.vue')['default']
    IconFont: typeof import('./src/components/IconFont/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    LayoutArea: typeof import('./src/components/Layout/LayoutArea.vue')['default']
    LayoutSection: typeof import('./src/components/Layout/LayoutSection.vue')['default']
    LayoutView: typeof import('./src/components/Layout/LayoutView.vue')['default']
    NavigationAvatar: typeof import('./src/components/Navigation/Avatar.vue')['default']
    NavigationNavBar: typeof import('./src/components/Navigation/NavBar.vue')['default']
    NavigationSideAction: typeof import('./src/components/Navigation/Side/SideAction.vue')['default']
    NavigationSideGoBack: typeof import('./src/components/Navigation/Side/SideGoBack.vue')['default']
    NavigationSideLogo: typeof import('./src/components/Navigation/Side/SideLogo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TooltipCustom: typeof import('./src/components/TooltipCustom/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
